name: Test
run-name: test cli-bash
on: [push]
jobs:
  test-cli-bash-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/checkout@v1
      - name: build tests
        working-directory: /tests
        run: cmake CMakeLists.txt && make && make test_commands && make test_analyzer
      - name: run tests commands
        run: ./test_commands
      - name: run tests analyzer
        run: ./test_analyzer
